Repository quokka-astro/quokka, pull requests merged in 2024-04, with the labels that each got.

#586 docs: add in-situ analysis
  docs/index.rst
  docs/insitu_analysis.rst
  docs/postprocessing.rst
Labels: documentation

#602 add "experimental" warning for AMD and Intel GPUs
  README.md
Labels: AMDGPU, blocking-release

#606 fix typo in TabulatedCooling
  src/TabulatedCooling.cpp
Labels: bug, blocking-release

#610 Use mass scalars while computing EOS quantities in NSCBC
  src/NSCBC_inflow.hpp
  src/NSCBC_outflow.hpp
Labels: bug

#615 If microphysics burn fails, retry hydro
  src/Chemistry.hpp
  src/RadhydroSimulation.hpp
Labels: enhancement
