Repository quokka-astro/quokka, pull requests merged in 2024-10, with the labels that each got.

#769 Avoid running out of disk space for regression testing
  .ci/azure-pipelines-regression.yml
Labels: CI, lgtm, size:XS

#767 Restructure: define ComputeModelBasedKappaEAndKappaP
  src/radiation/radiation_system.hpp
  src/radiation/source_terms_multi_group.hpp
Labels: lgtm, size:L

#771 Move enable_dust_gas_thermal_coupling_model to ISM_Traits
  src/QuokkaSimulation.hpp
  src/problems/RadBeam/test_radiation_beam.cpp
  src/problems/RadDust/test_rad_dust.cpp
  src/problems/RadDustMG/test_rad_dust_MG.cpp
  src/problems/RadForce/test_radiation_force.cpp
  src/problems/RadMarshak/test_radiation_marshak.cpp
  src/problems/RadMarshakAsymptotic/test_radiation_marshak_asymptotic.cpp
  src/problems/RadMarshakCGS/test_radiation_marshak_cgs.cpp
  src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
  src/problems/RadMarshakDustPE/test_radiation_marshak_dust_and_PE.cpp
  src/problems/RadMarshakVaytet/test_radiation_marshak_Vaytet.cpp
  src/problems/RadMatterCoupling/test_radiation_matter_coupling.cpp
  src/problems/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp
  src/problems/RadPulse/test_radiation_pulse.cpp
  src/problems/RadShadow/test_radiation_shadow.cpp
  src/problems/RadStreaming/test_radiation_streaming.cpp
  src/problems/RadStreamingY/test_radiation_streaming_y.cpp
  src/problems/RadSuOlson/test_radiation_SuOlson.cpp
  src/problems/RadTophat/test_radiation_tophat.cpp
  src/problems/RadTube/test_radiation_tube.cpp
  src/problems/RadhydroBB/test_radhydro_bb.cpp
  src/problems/RadhydroPulse/test_radhydro_pulse.cpp
  src/problems/RadhydroPulseDyn/test_radhydro_pulse_dyn.cpp
  src/problems/RadhydroPulseGrey/test_radhydro_pulse_grey.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/problems/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/problems/RadhydroShell/test_radhydro_shell.cpp
  src/problems/RadhydroShock/test_radhydro_shock.cpp
  src/problems/RadhydroShockCGS/test_radhydro_shock_cgs.cpp
  src/problems/RadhydroShockMultigroup/test_radhydro_shock_multigroup.cpp
  src/problems/RadhydroUniformAdvecting/test_radhydro_uniform_advecting.cpp
  src/radiation/radiation_system.hpp
Labels: lgtm, size:M

#773 Line cooling and cosmic ray heating
  src/math/interpolate.cpp
  src/problems/CMakeLists.txt
  src/problems/RadLineCooling/CMakeLists.txt
  src/problems/RadLineCooling/test_rad_line_cooling.cpp
  src/problems/RadLineCooling/test_rad_line_cooling.hpp
  src/problems/RadLineCoolingMG/CMakeLists.txt
  src/problems/RadLineCoolingMG/test_rad_line_cooling_MG.cpp
  src/problems/RadLineCoolingMG/test_rad_line_cooling_MG.hpp
  src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
  src/problems/RadhydroBB/test_radhydro_bb.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/radiation/radiation_dust_system.hpp
  src/radiation/radiation_system.hpp
  src/radiation/source_terms_multi_group.hpp
  src/radiation/source_terms_single_group.hpp
  tests/RadLineCooling.in
  tests/RadLineCoolingCoupled.in
Labels: lgtm, size:XXL

#784 Speed up unit tests by running ctest in parallel
  .github/workflows/cmake-macos.yml
  .github/workflows/cmake.yml
  .github/workflows/intel.yml
Labels: github_actions, lgtm, size:XS
