Repository quokka-astro/quokka, pull requests merged in 2024-12, with the labels that each got.

#808 add 'cellUpdates_ > 0' check
  src/QuokkaSimulation.hpp
  src/simulation.hpp
Labels: bug, lgtm, size:S

#804 fix openPMD plotfile output
  src/simulation.hpp
Labels: bug, lgtm, size:S

#812 use upload-artifact@v4
  .github/workflows/docs.yml
  .github/workflows/scorecard.yml
Labels: github_actions, lgtm, size:XS

#811 Use RSLA in all dust tests
  extern/data/dust/rad_dust_exact.csv
  extern/data/dust/rad_dust_exact_chat0.1.csv
  extern/data/dust/rad_dust_exact_chat0.8.csv
  src/problems/RadDust/test_rad_dust.cpp
  src/problems/RadDustMG/test_rad_dust_MG.cpp
  src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
  src/problems/RadMarshakDustPE/test_radiation_marshak_dust_and_PE.cpp
  src/radiation/radiation_dust_system.hpp
  tests/RadDust.in
  tests/RadMarshakDust.in
  tests/RadMarshakDustPEcoupled.in
  tests/RadMarshakDustPEdecoupled.in
Labels: lgtm, size:L

#816 Update ROCm version in dependencies_hip.sh
  .github/workflows/dependencies/dependencies_hip.sh
Labels: dependencies, github_actions, lgtm, size:S

#818 rename {x,y,z}-velocity to {x,y,z}-RiemannSolverVelocity in plotfiles
  src/QuokkaSimulation.hpp
Labels: lgtm, size:XS

#819 add print_cycle_timing runtime option
  src/simulation.hpp
  tests/benchmark_unigrid_1024.in
  tests/benchmark_unigrid_2048.in
  tests/benchmark_unigrid_4096.in
  tests/benchmark_unigrid_512.in
  tests/benchmark_unigrid_8192.in
Labels: enhancement, lgtm, size:M

#821 Update .clang-tidy
  src/.clang-tidy
Labels: bug, lgtm, size:XS

#822 Reduce walltime for RandomBlast regression test
  tests/RandomBlast_regression.in
Labels: lgtm, size:S

#823 Update cron schedule for regression tests
  .ci/azure-pipelines-regression.yml
Labels: CI, lgtm, size:XS

#828 Update .clang-tidy
  src/.clang-tidy
Labels: lgtm, size:XS
