Repository quokka-astro/quokka, pull requests merged in 2024-08, with the labels that each got.

#697 update docs for runtime parameters
  docs/parameters.rst
Labels: documentation, lgtm, size:XS

#704 Metal Advection Problem
  regression/quokka-tests.ini
  src/problems/CMakeLists.txt
  src/problems/MetalAdvectionProblem/CMakeLists.txt
  src/problems/MetalAdvectionProblem/data_sets.dat
  src/problems/MetalAdvectionProblem/test_sne.cpp
  src/problems/MetalAdvectionProblem/test_sne.hpp
  tests/metal_problem_regression.in
Labels: Setonix, lgtm, size:XL

#710 Revert "Metal Advection Problem"
  regression/quokka-tests.ini
  src/problems/CMakeLists.txt
  src/problems/MetalAdvectionProblem/CMakeLists.txt
  src/problems/MetalAdvectionProblem/data_sets.dat
  src/problems/MetalAdvectionProblem/test_sne.cpp
  src/problems/MetalAdvectionProblem/test_sne.hpp
  tests/metal_problem_regression.in
Labels: lgtm, size:XL

#709 fix Setonix compiler version
  scripts/setonix-gpu.profile
Labels: Setonix, lgtm, size:XS

#711 Upload results even if regression tests fail
  .ci/azure-pipelines-regression.yml
Labels: CI, lgtm, size:XS

#714 Cleanup: remove repeating calculation of kappa
  src/radiation/radiation_system.hpp
Labels: lgtm, size:L

#715 Dust temperature coupled to gas and radiation
  .gitignore
  extern/data/dust/rad_dust_exact.csv
  src/QuokkaSimulation.hpp
  src/problems/CMakeLists.txt
  src/problems/RadBeam/test_radiation_beam.cpp
  src/problems/RadDust/CMakeLists.txt
  src/problems/RadDust/test_rad_dust.cpp
  src/problems/RadDust/test_rad_dust.hpp
  src/problems/RadDustMG/CMakeLists.txt
  src/problems/RadDustMG/test_rad_dust_MG.cpp
  src/problems/RadDustMG/test_rad_dust_MG.hpp
  src/problems/RadForce/test_radiation_force.cpp
  src/problems/RadMarshak/test_radiation_marshak.cpp
  src/problems/RadMarshakAsymptotic/test_radiation_marshak_asymptotic.cpp
  src/problems/RadMarshakCGS/test_radiation_marshak_cgs.cpp
  src/problems/RadMarshakVaytet/test_radiation_marshak_Vaytet.cpp
  src/problems/RadMatterCoupling/test_radiation_matter_coupling.cpp
  src/problems/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp
  src/problems/RadPulse/test_radiation_pulse.cpp
  src/problems/RadShadow/test_radiation_shadow.cpp
  src/problems/RadStreaming/test_radiation_streaming.cpp
  src/problems/RadStreamingY/test_radiation_streaming_y.cpp
  src/problems/RadSuOlson/test_radiation_SuOlson.cpp
  src/problems/RadTophat/test_radiation_tophat.cpp
  src/problems/RadTube/test_radiation_tube.cpp
  src/problems/RadhydroBB/test_radhydro_bb.cpp
  src/problems/RadhydroPulse/test_radhydro_pulse.cpp
  src/problems/RadhydroPulseDyn/test_radhydro_pulse_dyn.cpp
  src/problems/RadhydroPulseGrey/test_radhydro_pulse_grey.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/problems/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/problems/RadhydroShell/test_radhydro_shell.cpp
  src/problems/RadhydroShock/test_radhydro_shock.cpp
  src/problems/RadhydroShockCGS/test_radhydro_shock_cgs.cpp
  src/problems/RadhydroShockMultigroup/test_radhydro_shock_multigroup.cpp
  src/problems/RadhydroUniformAdvecting/test_radhydro_uniform_advecting.cpp
  src/radiation/radiation_system.hpp
  tests/RadDust.in
Labels: lgtm, size:XL

#716 Make assertion work in the exchange step and dust temperature solution step
  src/QuokkaSimulation.hpp
  src/radiation/radiation_system.hpp
Labels: lgtm, size:M

#724 Redefine PRIMORDIAL_CHEM preprocessor as CHEMISTRY
  src/QuokkaSimulation.hpp
  src/chemistry/Chemistry.hpp
  src/hydro/EOS.hpp
  src/problems/PopIII/CMakeLists.txt
  src/problems/PrimordialChem/CMakeLists.txt
  tests/PopIII.in
  tests/primordial_chem.in
Labels: lgtm, size:M

#720 improve convergence rate of the radiation Newton-Raphson solver
  src/QuokkaSimulation.hpp
  src/problems/CMakeLists.txt
  src/problems/RadMarshakDust/CMakeLists.txt
  src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
  src/problems/RadMarshakDust/test_radiation_marshak_dust.hpp
  src/radiation/radiation_system.hpp
  tests/RadMarshakDust.in
Labels: enhancement, lgtm, size:L
