Repository quokka-astro/quokka, pull requests merged in 2024-09, with the labels that each got.

#731 Separate single- and multi-group radiation modules
  src/QuokkaSimulation.hpp
  src/problems/RadDust/test_rad_dust.cpp
  src/problems/RadDustMG/test_rad_dust_MG.cpp
  src/problems/RadMarshakVaytet/test_radiation_marshak_Vaytet.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/problems/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/problems/RadhydroShockMultigroup/test_radhydro_shock_multigroup.cpp
  src/radiation/radiation_system.hpp
  src/radiation/source_terms_multi_group.hpp
  src/radiation/source_terms_single_group.hpp
  tests/radshock_dimensionless.in
Labels: enhancement, lgtm, size:XXL

#734 Restructure AddSourceTermsMultiGroup
  src/QuokkaSimulation.hpp
  src/radiation/radiation_system.cpp
  src/radiation/radiation_system.hpp
  src/radiation/source_terms_multi_group.hpp
  src/radiation/source_terms_single_group.hpp
  tests/RadDust.in
Labels: lgtm, size:XXL

#733 A robust numerical scheme for the dust-gas coupling model
  src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
  src/radiation/planck_integral.hpp
  src/radiation/radiation_system.hpp
  src/radiation/source_terms_multi_group.hpp
  tests/RadMarshakDust.in
Labels: enhancement, lgtm, size:L

#741 Update Dockerfile
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  src/simulation.hpp
Labels: lgtm, size:M

#749 Create CODEOWNERS
  .github/CODEOWNERS
Labels: lgtm, size:S

#750 Restructure: put radiation flux update into a function
  src/radiation/radiation_system.hpp
  src/radiation/source_terms_multi_group.hpp
  src/radiation/source_terms_single_group.hpp
Labels: lgtm, size:L

#753 Update README.md to list Python as required
  README.md
Labels: documentation, lgtm, size:XS

#736 Add OpenSSF Security Scorecard action
  .github/workflows/scorecard.yml
  README.md
Labels: github_actions, lgtm, size:M

#751 Add a CUDA devcontainer
  .devcontainer/cuda-container/Dockerfile
  .devcontainer/cuda-container/devcontainer.json
  .devcontainer/gcc-container/Dockerfile
  .devcontainer/gcc-container/devcontainer.json
  scripts/mpirun-singleton-wrapper
  src/CMakeLists.txt
Labels: lgtm, size:L

#755 fix bug in make_tarball.py
  paper/make_tarball.py
Labels: bug, lgtm, size:XS
