Repository quokka-astro/quokka, pull requests merged in 2024-07, with the labels that each got.

#668 remove unnecessary EnforceLimits on old state
  src/RadhydroSimulation.hpp
Labels: lgtm

#671 no ghost cells in reference solution multifab
  src/RadhydroSimulation.hpp
Labels: lgtm, size:XS

#179 random blast ISM problem
  .gitignore
  extern/quadrature/quad.py
  regression/quokka-tests.ini
  src/AdvectionSimulation.hpp
  src/CMakeLists.txt
  src/RadhydroSimulation.hpp
  src/RandomBlast/CMakeLists.txt
  src/RandomBlast/blast.cpp
  src/RandomBlast/blast.hpp
  src/gauss.hpp
  src/quadrature.hpp
  src/simulation.hpp
  tests/RandomBlast.in
  tests/RandomBlast_regression.in
Labels: lgtm, size:XXL

#667 simplify EnforceLimits
  src/RadhydroSimulation.hpp
  src/hydro_system.hpp
  src/simulation.hpp
Labels: lgtm, size:L

#611 enable FPE traps in CI
  .github/workflows/cmake-macos.yml
  .github/workflows/intel.yml
  CMakeLists.txt
  src/Advection/CMakeLists.txt
  src/Advection2D/CMakeLists.txt
  src/AdvectionSemiellipse/CMakeLists.txt
  src/AdvectionSimulation.hpp
  src/BinaryOrbitCIC/CMakeLists.txt
  src/CMakeLists.txt
  src/FCQuantities/CMakeLists.txt
  src/HydroBlast3D/CMakeLists.txt
  src/HydroContact/CMakeLists.txt
  src/HydroHighMach/CMakeLists.txt
  src/HydroLeblanc/CMakeLists.txt
  src/HydroQuirk/CMakeLists.txt
  src/HydroSMS/CMakeLists.txt
  src/HydroShocktube/CMakeLists.txt
  src/HydroShocktubeCMA/CMakeLists.txt
  src/HydroShuOsher/CMakeLists.txt
  src/HydroVacuum/CMakeLists.txt
  src/HydroWave/CMakeLists.txt
  src/NSCBC/CMakeLists.txt
  src/ODEIntegration/CMakeLists.txt
  src/PassiveScalar/CMakeLists.txt
  src/PopIII/CMakeLists.txt
  src/PrimordialChem/CMakeLists.txt
  src/RadForce/CMakeLists.txt
  src/RadMarshak/CMakeLists.txt
  src/RadMarshakAsymptotic/CMakeLists.txt
  src/RadMarshakCGS/CMakeLists.txt
  src/RadMatterCoupling/CMakeLists.txt
  src/RadMatterCouplingRSLA/CMakeLists.txt
  src/RadPulse/CMakeLists.txt
  src/RadStreaming/CMakeLists.txt
  src/RadStreamingY/CMakeLists.txt
  src/RadSuOlson/CMakeLists.txt
  src/RadSuOlson/test_radiation_SuOlson.cpp
  src/RadTube/CMakeLists.txt
  src/RadTube/test_radiation_tube.cpp
  src/RadhydroPulse/CMakeLists.txt
  src/RadhydroPulseDyn/CMakeLists.txt
  src/RadhydroPulseGrey/CMakeLists.txt
  src/RadhydroPulseMG/CMakeLists.txt
  src/RadhydroPulseMGint/CMakeLists.txt
  src/RadhydroShock/CMakeLists.txt
  src/RadhydroShockCGS/CMakeLists.txt
  src/RadhydroShockMultigroup/CMakeLists.txt
  src/RadhydroSimulation.hpp
  src/RadhydroUniformAdvecting/CMakeLists.txt
  src/SphericalCollapse/CMakeLists.txt
  src/StarCluster/CMakeLists.txt
  src/main.cpp
  src/matplotlibcpp.h
Labels: enhancement, floating-point, CI, lgtm, size:M

#675 Fix Intel CI
  .github/workflows/intel.yml
Labels: CI, lgtm, size:XS

#676 update Setonix config
  scripts/setonix-cpu.profile
  scripts/setonix-gpu.profile
  src/ShockCloud/cloud.cpp
Labels: Setonix, lgtm, size:M

#677 update Setonix job scripts
  scripts/setonix-1node.submit
  scripts/setonix-64nodes.submit
  scripts/setonix-8nodes.submit
Labels: MPI bug, Setonix, lgtm, size:M

#678 PPL opacity models
  extern/Doppler-spectrum/exact_flux_density.csv
  src/CMakeLists.txt
  src/RadMarshakAsymptotic/test_radiation_marshak_asymptotic.cpp
  src/RadMarshakVaytet/CMakeLists.txt
  src/RadMarshakVaytet/test_radiation_marshak_Vaytet.cpp
  src/RadMarshakVaytet/test_radiation_marshak_Vaytet.hpp
  src/RadPulse/test_radiation_pulse.cpp
  src/RadTube/test_radiation_tube.cpp
  src/RadhydroBB/CMakeLists.txt
  src/RadhydroBB/test_radhydro_bb.cpp
  src/RadhydroBB/test_radhydro_bb.hpp
  src/RadhydroPulseMG/CMakeLists.txt
  src/RadhydroPulseMG/test_radhydro_pulse_MG.cpp
  src/RadhydroPulseMGconst/CMakeLists.txt
  src/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.hpp
  src/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/RadhydroShockMultigroup/test_radhydro_shock_multigroup.cpp
  src/radiation_system.hpp
  tests/MarshakVaytet.in
  tests/RadhydroBB.in
Labels: lgtm, size:XXL

#682 remove unused function ComputeSourceTermsExplicit
  src/radiation_system.hpp
Labels: lgtm, size:M

#687 Add VSCode/Codespaces Dev Container settings
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement, lgtm, size:M

#688 fix Sphinx warnings
  docs/api.rst
  docs/conf.py
  docs/debugging.rst
  docs/error_checking.rst
  docs/howto_clang_tidy.rst
  docs/index.rst
  docs/insitu_analysis.rst
  docs/instability.rst
  docs/performance.rst
  docs/postprocessing.rst
  docs/running_on_hpc_clusters.rst
  docs/tests/radhydro_pulse.rst
Labels: documentation, lgtm, size:M

#684 Clean up code for single-group radiation
  src/RadhydroSimulation.hpp
  src/problems/RadBeam/test_radiation_beam.cpp
  src/problems/RadForce/test_radiation_force.cpp
  src/problems/RadMarshak/test_radiation_marshak.cpp
  src/problems/RadMarshakAsymptotic/CMakeLists.txt
  src/problems/RadMarshakAsymptotic/test_radiation_marshak_asymptotic.cpp
  src/problems/RadMarshakCGS/test_radiation_marshak_cgs.cpp
  src/problems/RadMatterCoupling/test_radiation_matter_coupling.cpp
  src/problems/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp
  src/problems/RadPulse/test_radiation_pulse.cpp
  src/problems/RadShadow/test_radiation_shadow.cpp
  src/problems/RadStreaming/test_radiation_streaming.cpp
  src/problems/RadStreamingY/test_radiation_streaming_y.cpp
  src/problems/RadSuOlson/test_radiation_SuOlson.cpp
  src/problems/RadTophat/test_radiation_tophat.cpp
  src/problems/RadTube/test_radiation_tube.cpp
  src/problems/RadhydroBB/test_radhydro_bb.cpp
  src/problems/RadhydroPulse/test_radhydro_pulse.cpp
  src/problems/RadhydroPulseDyn/test_radhydro_pulse_dyn.cpp
  src/problems/RadhydroPulseGrey/test_radhydro_pulse_grey.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/problems/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/problems/RadhydroShell/test_radhydro_shell.cpp
  src/problems/RadhydroShock/test_radhydro_shock.cpp
  src/problems/RadhydroShockCGS/test_radhydro_shock_cgs.cpp
  src/problems/RadhydroShockMultigroup/test_radhydro_shock_multigroup.cpp
  src/problems/RadhydroUniformAdvecting/test_radhydro_uniform_advecting.cpp
  src/radiation/radiation_system.hpp
  tests/MarshakAsymptoticCorr.in
Labels: enhancement, lgtm, size:XL

#690 Update citations
  docs/citation.rst
  docs/references.bib
Labels: documentation, lgtm, size:S

#691 add equations to docs
  docs/equations.rst
Labels: documentation, lgtm, size:M
