Repository quokka-astro/quokka, pull requests merged in 2025-09, with the labels that each got.

#1297 Fix bug in getParticleDataAtAllLevels()
  inputs/SphericalCollapse.in
  src/particles/PhysicsParticles.hpp
  src/particles/particle_IO.hpp
  src/problems/GravRadParticle3D/test_grav_rad_particle_3D.cpp
  src/problems/ParticleSinkFormation/test_particle_sink_formation.cpp
Labels: particles, lgtm, size:M

#1298 Revert "Balsara Method for ComputeEMF"
  docs/markdown/parameters.md
  src/QuokkaSimulation.hpp
  src/hydro/mhd_system.hpp
Labels: MHD, lgtm, size:L

#1257 Update Setonix profile
  docs/markdown/running_on_hpc_clusters.md
  scripts/hpc_profiles/setonix-gpu.profile
  scripts/slurm/setonix-1node.submit
  scripts/slurm/setonix-64nodes.submit
  scripts/slurm/setonix-8nodes.submit
Labels: Setonix, lgtm, size:M

#1323 Making ParticleToMesh reproducible by rounding off rhs at 12th digit.
  src/simulation.hpp
Labels: particles, lgtm, size:M

#1310 Setting custom boundary conditions on faces based on direction
  inputs/brio_wu_shocktube.in
  src/QuokkaSimulation.hpp
  src/problems/BrioWuShockTube/CMakeLists.txt
  src/problems/BrioWuShockTube/test_brio_wu_shocktube.cpp
  src/problems/CMakeLists.txt
  src/simulation.hpp
Labels: lgtm, size:L

#1324 Update regression tests
  inputs/SphericalCollapseAMR_regression.in
  inputs/SphericalCollapse_regression.in
  regression/quokka-tests.ini
  src/problems/SphericalCollapse/spherical_collapse.cpp
Labels: lgtm, size:L

#1333 add AGENTS.md
  AGENTS.md
Labels: documentation, lgtm, size:S

#1335 Remove obsolete cooling modules
  docs/markdown/parameters.md
  inputs/Cooling.in
  inputs/ODE.in
  inputs/RandomBlast.in
  inputs/RandomBlastAMR_regression.in
  inputs/RandomBlast_regression.in
  inputs/SN_long_grackle.in
  inputs/ShockCloud_32.in
  inputs/ShockCloud_64.in
  src/CMakeLists.txt
  src/QuokkaSimulation.hpp
  src/cooling/CloudyDataReader.cpp
  src/cooling/CloudyDataReader.hpp
  src/cooling/GrackleDataReader.cpp
  src/cooling/GrackleDataReader.hpp
  src/cooling/GrackleLikeCooling.cpp
  src/cooling/GrackleLikeCooling.hpp
  src/cooling/TabulatedCooling.cpp
  src/cooling/TabulatedCooling.hpp
  src/problems/RandomBlast/blast.cpp
  src/problems/ResampledCoolingTest/CMakeLists.txt
  src/problems/ResampledCoolingTest/test_resampled_cooling.cpp
  src/problems/SN/test_SN.cpp
  src/problems/ShockCloud/cloud.cpp
Labels: lgtm, size:XXL

#1338 fix error in debug.yml
  .github/workflows/cmake-arm64-debug.yml
  .github/workflows/cmake-arm64-release.yml
  src/hydro/hydro_system.hpp
Labels: github_actions, lgtm, size:M

#1350 Add documentation for creating problem generators
  docs/markdown/developing_problem_generators.md
  docs/markdown/index.md
Labels: documentation, size:M, codex

#1347 Update docs
  docs/markdown/amr_grid_refinement.md
  docs/markdown/amr_grid_refinement.svg
  docs/markdown/citation.md
  docs/markdown/references.bib
  docs/markdown/star_formation.md
  docs/mkdocs.yml
  inputs/blast2d_amr_example.in
Labels: documentation, lgtm, size:L

#1349 Add developer onboarding notes
  docs/markdown/developer_onboarding.md
Labels: documentation, lgtm, size:M, codex

#1351 Improve reference solution checks (handle zero-norm cases)
  src/QuokkaSimulation.hpp
Labels: lgtm, size:M, bug: usability

#1359 Fix broken source links in documentation guides
  docs/markdown/developer_onboarding.md
  docs/markdown/developing_problem_generators.md
Labels: documentation, lgtm, size:M, codex
