Repository quokka-astro/quokka, pull requests merged in 2025-06, with the labels that each got.

#1120 add BL_PROFILE annotations to particle functions
  src/QuokkaSimulation.hpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_accretion.hpp
  src/particles/particle_creation.hpp
  src/particles/particle_deposition.hpp
  src/particles/particle_destruction.hpp
  src/simulation.hpp
Labels: particles, lgtm, size:M

#1133 Reduce communication in kickParticlesAllLevels
  src/simulation.hpp
Labels: particles, lgtm, size:L

#1131 Cooling: use functors instead of function pointers
  src/cooling/GrackleLikeCooling.hpp
  src/cooling/TabulatedCooling.hpp
  src/math/ODEIntegrate.hpp
  src/problems/ODEIntegration/test_ode.cpp
Labels: lgtm, size:L

#1137 Fix bugs in SF and SN prescriptions
  src/particles/particle_creation.hpp
  src/particles/particle_deposition.hpp
  src/problems/ParticleSF/test_particle_SF.cpp
  src/problems/ParticleSF/test_particle_SF.hpp
  tests/ParticleSF.in
Labels: bug: wrong answer/failure/crash, particles, lgtm, size:L

#1141 Delete .github/workflows/intel.yml
  .github/workflows/intel.yml
Labels: github_actions, lgtm, size:M

#1105 Optimize github pipelines
  .circleci/config.yml
  .circleci/continue-config.yml
  .github/workflows/check_changes.yml
  .github/workflows/checkpoint-restart.yml
  .github/workflows/clang-tidy.yml
  .github/workflows/cmake-macos.yml
  .github/workflows/cmake.yml
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/hip.yml
  .github/workflows/openpmd.yml
  .github/workflows/warnings.yml
Labels: github_actions, lgtm, size:L

#1146 Fix bug introduced in PR #1111
  src/simulation.hpp
Labels: bug: wrong answer/failure/crash, lgtm, size:S

#1150 Update more paths to input files
  regression/quokka-tests.ini
  src/problems/ParticleSF/CMakeLists.txt
Labels: lgtm, size:M

#1153 A fix to the CodeQL problem
  .github/workflows/codeql.yml
Labels: github_actions, lgtm, size:S

#1152 Replace CTest runner with Canary
  .github/workflows/cmake-arm64-debug.yml
  .github/workflows/cmake-arm64-hwasan.yml
  .github/workflows/cmake-arm64-release.yml
  .github/workflows/cmake-macos.yml
  .github/workflows/cmake.yml
Labels: github_actions, lgtm, size:M

#1155 Delete cmake directory
  cmake/CodeCoverage.cmake
  cmake/altra_gcc.cmake
  cmake/avatar_gcc_cuda.cmake
  cmake/avatar_llvm_cuda.cmake
  cmake/avatar_nvhpc_cuda.cmake
  cmake/avatar_oneapi_cuda.cmake
  cmake/crusher.cmake
  cmake/delta_gcc_cuda.cmake
  cmake/delta_gcc_hip.cmake
  cmake/gadi_gcc_cuda.cmake
  cmake/gadi_llvm_cuda.cmake
  cmake/gadi_oneapi_cuda.cmake
  cmake/setonix.cmake
  cmake/summit.cmake
  cmake/ubuntu_aocc.cmake
  cmake/ubuntu_aocc_cuda.cmake
Labels: lgtm, size:XL

#1156 Reorganize scripts directory
  scripts/bash/make_movie.sh
  scripts/bash/mpirun-singleton-wrapper.sh
  scripts/bash/slurm_job_monitor.sh
  scripts/bash/tidy.sh
  scripts/blast_1gpu.submit
  scripts/blast_1node.submit
  scripts/cpu-setonix.sh
  scripts/crusher-1node.submit
  scripts/hpc_profiles/delta_ai.profile
  scripts/hpc_profiles/frontier.profile
  scripts/hpc_profiles/moth-sanitizer.profile
  scripts/hpc_profiles/moth.profile
  scripts/hpc_profiles/setonix-gpu.profile
  scripts/mi100-1gpu.submit
  scripts/mi100-1node.submit
  scripts/pbs/amr-shell-1node-1stream.pbs
  scripts/pbs/amr-shell-1node.pbs
  scripts/pbs/amr-shell-2nodes.pbs
  scripts/pbs/amr-shell-4nodes.pbs
  scripts/pbs/amr-shell-8nodes.pbs
  scripts/pbs/cpu-sedov-1node.pbs
  scripts/pbs/cpu-sedov-64nodes.pbs
  scripts/pbs/cpu-sedov-8nodes.pbs
  scripts/pbs/gpu_wrapper_amr_shell.sh
  scripts/pbs/gpu_wrapper_amr_shell_stream.sh
  scripts/pbs/gpu_wrapper_cooling_1024.sh
  scripts/pbs/gpu_wrapper_sedov_1024.sh
  scripts/pbs/gpu_wrapper_sedov_2048.sh
  scripts/pbs/gpu_wrapper_sedov_256.sh
  scripts/pbs/gpu_wrapper_sedov_512.sh
  scripts/pbs/gpu_wrapper_shell_1024.sh
  scripts/pbs/gpu_wrapper_shell_2048.sh
  scripts/pbs/gpu_wrapper_shell_256.sh
  scripts/pbs/gpu_wrapper_shell_512.sh
  scripts/pbs/sedov-1gpu.pbs
  scripts/pbs/sedov-1node-mpich.pbs
  scripts/pbs/sedov-1node.pbs
  scripts/pbs/sedov-64nodes-mpich.pbs
  scripts/pbs/sedov-64nodes.pbs
  scripts/pbs/sedov-8nodes-mpich.pbs
  scripts/pbs/sedov-8nodes.pbs
  scripts/pbs/shell-1gpu.pbs
  scripts/pbs/shell-1node.pbs
  scripts/pbs/shell-64nodes.pbs
  scripts/pbs/shell-8nodes.pbs
  scripts/python/plot_PDF_2D_outputs.py
  scripts/slurm/dtai-1node.submit
  scripts/slurm/dtai-64node.submit
  scripts/slurm/dtai-8node.submit
  scripts/slurm/frontier-1node.submit
  scripts/slurm/frontier-4096node.submit
  scripts/slurm/frontier-512node.submit
  scripts/slurm/frontier-64node.submit
  scripts/slurm/frontier-8node.submit
  scripts/slurm/setonix-1node.submit
  scripts/slurm/setonix-64nodes.submit
  scripts/slurm/setonix-8nodes.submit
Labels: lgtm, size:L

#1016 Dockerfile for CI agents on moth and avatargpu
  .devcontainer/cuda-azp-agent-in-docker/Dockerfile
  .devcontainer/cuda-azp-agent-in-docker/build.sh
  .devcontainer/cuda-azp-agent-in-docker/start.sh
  .devcontainer/rocm-azp-agent-in-docker/Dockerfile
  .devcontainer/rocm-azp-agent-in-docker/build.sh
  .devcontainer/rocm-azp-agent-in-docker/start.sh
  .devcontainer/rocm-container/build-by-step.sh
  .devcontainer/rocm-container/build.sh
Labels: do not merge, lgtm, size:L

#1164 use ResampledCooling module for ShockCloud regression test
  inputs/ShockCloud_64_regression.in
  regression/quokka-tests.ini
Labels: lgtm, size:XS
