Repository quokka-astro/quokka, pull requests merged in 2025-05, with the labels that each got.

#1025 Update Dockerfile to use ROCm 6.4
  .devcontainer/rocm-container/Dockerfile
Labels: lgtm, size:S

#966 Stochastic Stellar Population
  docs/markdown/star_formation.md
  src/particles/PhysicsParticles.hpp
  src/particles/particle_creation.hpp
  src/particles/stellarpop_data.hpp
  src/problems/ParticleCreation/CMakeLists.txt
  src/problems/ParticleCreation/particle_creation_from_cell.cpp
  src/problems/ParticleCreation/particle_creation_from_cell.hpp
  src/problems/ParticleSink/CMakeLists.txt
  src/problems/ParticleSink/test_particle_sink.hpp
  src/problems/SN/CMakeLists.txt
  src/problems/SN/test_SN.cpp
Labels: enhancement, particles, lgtm, size:L

#1036 Merge #1035 into agora-galaxy branch
  src/math/interpolate.cpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_creation.hpp
  src/particles/particle_types.hpp
  src/particles/stellarpop_data.hpp
  src/problems/CMakeLists.txt
  src/problems/ParticleCreation/particle_creation_from_cell.cpp
  src/problems/ParticleSF/CMakeLists.txt
  src/problems/ParticleSF/test_particle_SF.cpp
  src/problems/ParticleSF/test_particle_SF.hpp
  tests/ParticleSF.in
Labels: particles, lgtm, size:XL

#1048 Include interpolate.cpp and fextract.cpp in src/CMakeLists
  src/CMakeLists.txt
  src/problems/Advection/CMakeLists.txt
  src/problems/AdvectionSemiellipse/CMakeLists.txt
  src/problems/FCQuantities/CMakeLists.txt
  src/problems/GravRadParticle3D/CMakeLists.txt
  src/problems/HydroContact/CMakeLists.txt
  src/problems/HydroHighMach/CMakeLists.txt
  src/problems/HydroLeblanc/CMakeLists.txt
  src/problems/HydroSMS/CMakeLists.txt
  src/problems/HydroShocktube/CMakeLists.txt
  src/problems/HydroShocktubeCMA/CMakeLists.txt
  src/problems/HydroShuOsher/CMakeLists.txt
  src/problems/HydroVacuum/CMakeLists.txt
  src/problems/HydroWave/CMakeLists.txt
  src/problems/NSCBC/CMakeLists.txt
  src/problems/ParticleCreation/CMakeLists.txt
  src/problems/ParticleSink/CMakeLists.txt
  src/problems/PassiveScalar/CMakeLists.txt
  src/problems/RadDust/CMakeLists.txt
  src/problems/RadDustMG/CMakeLists.txt
  src/problems/RadForce/CMakeLists.txt
  src/problems/RadLineCooling/CMakeLists.txt
  src/problems/RadLineCoolingMG/CMakeLists.txt
  src/problems/RadMarshak/CMakeLists.txt
  src/problems/RadMarshakAsymptotic/CMakeLists.txt
  src/problems/RadMarshakCGS/CMakeLists.txt
  src/problems/RadMarshakDust/CMakeLists.txt
  src/problems/RadMarshakDustPE/CMakeLists.txt
  src/problems/RadMarshakVaytet/CMakeLists.txt
  src/problems/RadMatterCoupling/CMakeLists.txt
  src/problems/RadMatterCouplingRSLA/CMakeLists.txt
  src/problems/RadParticle/CMakeLists.txt
  src/problems/RadParticle2D/CMakeLists.txt
  src/problems/RadPulse/CMakeLists.txt
  src/problems/RadStreaming/CMakeLists.txt
  src/problems/RadStreamingY/CMakeLists.txt
  src/problems/RadSuOlson/CMakeLists.txt
  src/problems/RadTube/CMakeLists.txt
  src/problems/RadhydroBB/CMakeLists.txt
  src/problems/RadhydroPulse/CMakeLists.txt
  src/problems/RadhydroPulseDyn/CMakeLists.txt
  src/problems/RadhydroPulseGrey/CMakeLists.txt
  src/problems/RadhydroPulseMGconst/CMakeLists.txt
  src/problems/RadhydroPulseMGint/CMakeLists.txt
  src/problems/RadhydroShell/CMakeLists.txt
  src/problems/RadhydroShock/CMakeLists.txt
  src/problems/RadhydroShockCGS/CMakeLists.txt
  src/problems/RadhydroShockMultigroup/CMakeLists.txt
  src/problems/RadhydroUniformAdvecting/CMakeLists.txt
  src/problems/SN/CMakeLists.txt
Labels: lgtm, size:M

#1060 Move contributing guide to docs
  CONTRIBUTING.md
  docs/markdown/contributing.md
  docs/mkdocs.yml
Labels: documentation, lgtm, size:XL

#1059 Update gallery with AGORA sim
  docs/markdown/gallery.md
Labels: documentation, lgtm, size:XS

#1056 Add a simple script to run clang-tidy on modified files
  docs/markdown/howto_clang_tidy.md
  scripts/tidy.sh
Labels: documentation, lgtm, size:L

#1055 Implement the Krumholz 2004 model for sink particle accretion
  src/particles/PhysicsParticles.hpp
  src/particles/particle_accretion.hpp
  src/particles/particle_types.hpp
  src/particles/particle_utils.hpp
  src/problems/ParticleSink/test_particle_sink.cpp
  src/simulation.hpp
  tests/ParticleSink.in
  tests/Sink_4.txt
Labels: enhancement, particles, lgtm, size:L

#1063 allow supercycling of Poisson solves
  src/simulation.hpp
Labels: enhancement, lgtm, size:S

#1066 Change output behaviour
  src/simulation.hpp
  tests/ParticleCreation.in
Labels: enhancement, lgtm, size:XS

#1070 Add `using Real = amrex::Real;`
  src/physics_info.hpp
Labels: lgtm, size:XS

#1057 add example SLURM script to cancel job when I/O hangs
  scripts/slurm_job_monitor.sh
Labels: I/O, lgtm, size:M

#1079 add MPI_Barrier after writing each level in checkpoint files
  src/simulation.hpp
Labels: I/O, lgtm, size:XS

#1018 add Viskores build to dev containers
  .devcontainer/cuda-container/Dockerfile
  .devcontainer/gcc-container/Dockerfile
  .devcontainer/rocm-container/Dockerfile
Labels: CI, lgtm, size:M, docker, viz

#1080 Fix volume rendering
  docs/markdown/insitu_analysis.md
  docs/markdown/volume_render_sphere.png
  src/simulation.hpp
  tests/ascent_actions.yaml
Labels: lgtm, size:M, library bug, bug: usability, viz

#1082 Add a DeepWiki badge to README to allow auto-refreshing deepwiki page
  README.md
Labels: documentation, lgtm, size:XS

#1084 set FPE strict mode to avoid spurious FPEs with AppleClang
  CMakeLists.txt
Labels: lgtm, size:XS

#1083 change default SNScheme to hybrid thermal/momentum and use AMREX_ENUM
  src/particles/particle_types.hpp
  tests/ParticleSink.in
  tests/SN.in
Labels: particles, lgtm, size:S

#1071 Add plotfilemf_fc
  src/QuokkaSimulation.hpp
  src/problems/CMakeLists.txt
  src/problems/HydroWaveFC/CMakeLists.txt
  src/problems/HydroWaveFC/test_hydro_wave_fc.cpp
  src/problems/HydroWaveFC/test_hydro_wave_fc.hpp
  src/simulation.hpp
  tests/hydro_wave_fc.in
Labels: enhancement, lgtm, size:L

#1052 fix all tidy and warnings of compute-emf
  src/problems/AlfvenWaveCircular/test_alfven_wave_circular.cpp
  src/problems/FastWave/test_fast_wave.cpp
  src/problems/FastWave2/test_fast_wave_perm2.cpp
  src/problems/FastWave3/test_fast_wave_perm3.cpp
Labels: lgtm, size:L

#1072 Add Bondi accretion test from Krumholz 2004
  src/particles/particle_accretion.hpp
  src/problems/CMakeLists.txt
  src/problems/ParticleAccretion/CMakeLists.txt
  src/problems/ParticleAccretion/test_particle_accretion.cpp
  src/problems/ParticleAccretion/test_particle_accretion.hpp
  src/problems/ParticleSink/test_particle_sink.cpp
  tests/ParticleAccretion.in
  tests/sink.txt
Labels: particles, lgtm, size:L

#1091 Fix bug caused by function rename in #1071
  src/simulation.hpp
Labels: bug: wrong answer/failure/crash, lgtm, size:XS

#1088 Frontier-like docker container
  .devcontainer/rocm-container/Dockerfile
  .devcontainer/rocm-container/rocm_so.conf
Labels: lgtm, size:L

#1097 remove tidy check pointer-arithmetic
  src/.clang-tidy
Labels: lgtm, size:XS

#1102 update CLAUDE.md
  CLAUDE.md
Labels: documentation, lgtm, size:M

#1114 Ensure runtime parameters override compile-time settings
  src/QuokkaSimulation.hpp
  src/simulation.hpp
  tests/hydro_wave_fc.in
Labels: lgtm, size:S

#1108 Update simulation.hpp to fix plotfileMF_fc bug
  src/problems/CMakeLists.txt
  src/problems/HydroWave/CMakeLists.txt
  src/problems/HydroWave/test_hydro_wave.cpp
  src/problems/HydroWaveFC/CMakeLists.txt
  src/problems/HydroWaveFC/test_hydro_wave_fc.cpp
  src/simulation.hpp
  tests/hydro_wave.in
Labels: bug: wrong answer/failure/crash, lgtm, size:L

#1035 Validate stochastic star formation algorithm
  docs/markdown/star_formation.md
  docs/mkdocs.yml
  extern/ChabrierIMFCalculations.nb
  src/math/interpolate.cpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_creation.hpp
  src/particles/particle_types.hpp
  src/particles/stellarpop_data.hpp
  src/problems/CMakeLists.txt
  src/problems/ParticleCreation/particle_creation_from_cell.cpp
  src/problems/ParticleSF/CMakeLists.txt
  src/problems/ParticleSF/test_particle_SF.cpp
  src/problems/ParticleSF/test_particle_SF.hpp
  src/simulation.hpp
  tests/ParticleSF.in
Labels: bug: wrong answer/failure/crash, particles, lgtm, size:XXL
