Repository quokka-astro/quokka, pull requests merged in 2025-07, with the labels that each got.

#1165 Compute ghost wavespeeds and face velocities
  inputs/hydro_wave.in
  scripts/python/plot_face_velocities.py
  src/QuokkaSimulation.hpp
  src/hydro/NSCBC_inflow.hpp
  src/hydro/NSCBC_outflow.hpp
  src/hydro/hydro_system.hpp
  src/linear_advection/AdvectionSimulation.hpp
  src/linear_advection/linear_advection.hpp
  src/simulation.hpp
Labels: lgtm, size:XXL

#1183 Don't store face velocities in state_fc_
  src/QuokkaSimulation.hpp
  src/physics_info.hpp
  src/physics_numVars.hpp
  src/simulation.hpp
Labels: lgtm, size:M

#1186 Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: github_actions, lgtm, size:L

#1189 Fix face-centered plotfile output failing when plotfile directory already exists
  src/simulation.hpp
Labels: bug: wrong answer/failure/crash, lgtm, size:XS

#1188 Remove all AMREX_PARTICLES ifdef blocks
  src/QuokkaSimulation.hpp
  src/simulation.hpp
Labels: particles, lgtm, size:S

#1187 Add QED II/III papers to citation page
  docs/markdown/citation.md
  docs/markdown/references.bib
Labels: documentation, lgtm, size:M

#1193 Update claude-code-review.yml
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: github_actions, lgtm, size:M

#1194 Fix fextract function for MPI-parallel runs
  src/util/fextract.cpp
Labels: lgtm, size:S

#1207 docs: add comprehensive AMR grid refinement guide
  docs/markdown/amr_grid_refinement.md
  docs/mkdocs.yml
Labels: documentation, lgtm, size:L

#1212 Add timestep drop detector (dt_cutoff parameter)
  docs/markdown/parameters.md
  src/simulation.hpp
Labels: lgtm, size:S

#1218 always-success job for codeql
  .github/workflows/codeql.yml
Labels: github_actions, lgtm, size:M

#1222 Add bounds_error parameter to interpolate_value function
  src/CMakeLists.txt
  src/math/interpolate.cpp
  src/math/interpolate.hpp
  src/particles/stellarpop_data.hpp
  src/problems/ParticleAccretion/test_particle_accretion.cpp
  src/problems/ParticleSF/CMakeLists.txt
  src/problems/ParticleSinkFormation/CMakeLists.txt
Labels: lgtm, size:L

#1227 Refuse to run if ncells < nghost_cc_
  inputs/MatterEnergyExchangeRSLA.in
  inputs/ResampledCooling.in
  inputs/TabulatedCooling.in
  inputs/energyexchange.in
  inputs/primordial_chem.in
  src/simulation.hpp
Labels: lgtm, size:S

#1215 Implement user-specified particle radiation
  inputs/ParticleRadiation.in
  inputs/TestParticlesNoRad.txt
  src/QuokkaSimulation.hpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_radiation.hpp
  src/problems/CMakeLists.txt
  src/problems/ParticleRadiation/CMakeLists.txt
  src/problems/ParticleRadiation/particle_radiation.cpp
  src/problems/ParticleSink/test_particle_sink.cpp
  src/radiation/radiation_system.hpp
  src/simulation.hpp
Labels: enhancement, particles, lgtm, size:L

#1115 Update Bondi accretion test
  inputs/ParticleAccretion.in
  inputs/ParticleAccretionBH.in
  inputs/sink.txt
  inputs/sink_moving.txt
  src/particles/PhysicsParticles.hpp
  src/particles/particle_accretion.hpp
  src/particles/particle_types.hpp
  src/problems/ParticleAccretion/CMakeLists.txt
  src/problems/ParticleAccretion/test_particle_accretion.cpp
Labels: bug: wrong answer/failure/crash, particles, lgtm, size:XL

#900 Compute emf
  .github/workflows/mhd.yml
  docs/markdown/parameters.md
  inputs/alfven_wave_circular.in
  inputs/alfven_wave_linear.in
  inputs/current_sheet.in
  inputs/fast_wave.in
  inputs/field_loop.in
  inputs/orszag_tang.in
  scripts/read_fc_print.py
  src/QuokkaSimulation.hpp
  src/hydro/EOS.hpp
  src/hydro/HLLD.hpp
  src/hydro/HydroState.hpp
  src/hydro/LLF_mhd.hpp
  src/hydro/hydro_system.hpp
  src/hydro/mhd_system.hpp
  src/hyperbolic_system.hpp
  src/problems/AlfvenWaveCircular/CMakeLists.txt
  src/problems/AlfvenWaveCircular/test_alfven_wave_circular.cpp
  src/problems/AlfvenWaveLinear/CMakeLists.txt
  src/problems/AlfvenWaveLinear/test_alfven_wave_linear.cpp
  src/problems/CMakeLists.txt
  src/problems/CurrentSheet/CMakeLists.txt
  src/problems/CurrentSheet/test_current_sheet.cpp
  src/problems/FCQuantities/CMakeLists.txt
  src/problems/FastWave/CMakeLists.txt
  src/problems/FastWave/test_fast_wave.cpp
  src/problems/FastWave/test_fast_wave.hpp
  src/problems/FieldLoop/CMakeLists.txt
  src/problems/FieldLoop/test_field_loop.cpp
  src/problems/OrszagTang/CMakeLists.txt
  src/problems/OrszagTang/test_orszag_tang.cpp
  src/simulation.hpp
Labels: enhancement, MHD, lgtm, size:XXL

#1240 rename numRadVars to numRadVarsPerGroup
  src/QuokkaSimulation.hpp
  src/physics_info.hpp
  src/physics_numVars.hpp
  src/problems/ParticleRadiation/particle_radiation.cpp
  src/problems/RadDustMG/test_rad_dust_MG.cpp
  src/problems/RadForce/test_radiation_force.cpp
  src/problems/RadLineCoolingMG/test_rad_line_cooling_MG.cpp
  src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
  src/problems/RadMarshakDustPE/test_radiation_marshak_dust_and_PE.cpp
  src/problems/RadMarshakVaytet/test_radiation_marshak_Vaytet.cpp
  src/problems/RadParticle/test_radparticle.cpp
  src/problems/RadStreaming/test_radiation_streaming.cpp
  src/problems/RadTube/test_radiation_tube.cpp
  src/problems/RadhydroBB/test_radhydro_bb.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/problems/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/problems/RadhydroShockMultigroup/test_radhydro_shock_multigroup.cpp
  src/radiation/radiation_system.hpp
Labels: lgtm, size:L
