Repository quokka-astro/quokka, pull requests merged in 2025-03, with the labels that each got.

#921 add safety check in ComputeEddingtonTensor to avoid FPE error
  src/radiation/radiation_system.hpp
Labels: bug: wrong answer/failure/crash, lgtm, size:S

#922 update Setonix script to use ROCm 6.3
  scripts/setonix-1node.submit
  scripts/setonix-64nodes.submit
  scripts/setonix-8nodes.submit
  scripts/setonix-gpu.profile
Labels: Setonix, AMDGPU, lgtm, size:M

#911 Compile-time particle switch with Bitwise Operations
  src/particles/PhysicsParticles.hpp
  src/particles/particle_creation.hpp
  src/particles/particle_deposition.hpp
  src/particles/particle_types.hpp
  src/physics_info.hpp
  src/problems/BinaryOrbitCIC/binary_orbit.cpp
  src/problems/GravRadParticle3D/test_grav_rad_particle_3D.cpp
  src/problems/Gravity3D/gravity_3d.cpp
  src/problems/RadParticle/test_radparticle.cpp
  src/problems/RadParticle2D/test_radparticle_2D.cpp
  src/problems/SphericalCollapse/spherical_collapse.cpp
  src/simulation.hpp
  tests/BinaryOrbit.in
  tests/Gravity3D.in
  tests/RadParticles1D.in
  tests/RadParticles2D.in
  tests/SphericalCollapse.in
Labels: particles, lgtm, size:XXL

#923 A clean fix of the FPE issue on moth
  .ci/azure-pipelines-amdgpu.yml
  .github/workflows/hip.yml
  src/problems/SphericalCollapse/CMakeLists.txt
  src/radiation/radiation_system.hpp
Labels: lgtm, size:M

#924 Mermaid flowchart
  .github/workflows/docs.yml
  .pre-commit-config.yaml
  docs/docs/flowchart-v2.jpg
  docs/docs/flowchart-v2.pdf
  docs/docs/flowchart.md
  docs/docs/flowchart.svg
  docs/mkdocs.yml
  docs/requirements.txt
Labels: documentation, lgtm, size:M

#926 Allow creating multiple particle from one cell.
  src/particles/particle_creation.hpp
  src/problems/Gravity3D/gravity_3d.cpp
Labels: enhancement, particles, lgtm, size:M

#927 Particle destructor
  src/particles/PhysicsParticles.hpp
  src/particles/particle_creation.hpp
  src/particles/particle_destruction.hpp
  src/particles/particle_types.hpp
  src/problems/Gravity3D/gravity_3d.cpp
  src/simulation.hpp
  tests/Gravity3D.in
Labels: particles, lgtm, size:L

#931 remove workarounds from Setonix job scripts
  scripts/setonix-1node.submit
  scripts/setonix-64nodes.submit
  scripts/setonix-8nodes.submit
Labels: Setonix, lgtm, size:S

#928 Movie from QED I paper
  docs/docs/gallery.md
Labels: lgtm, size:S

#935 Make metadata.yaml structured and add Fields.yaml in particle plotfile
  src/QuokkaSimulation.hpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_types.hpp
  src/problems/ShockCloud/cloud.cpp
  src/simulation.hpp
  tests/Gravity3D.in
Labels: particles, lgtm, size:L

#937 add OpenPMD CI action
  .github/workflows/openpmd.yml
Labels: CI, lgtm, size:M

#941 Remove all unused const variables
  src/problems/RadLineCooling/test_rad_line_cooling.cpp
  src/problems/RadMarshak/test_radiation_marshak.cpp
  src/problems/RadMarshakAsymptotic/test_radiation_marshak_asymptotic.cpp
  src/problems/RadMarshakCGS/test_radiation_marshak_cgs.cpp
  src/problems/RadMarshakDustPE/test_radiation_marshak_dust_and_PE.cpp
  src/problems/RadMatterCoupling/test_radiation_matter_coupling.cpp
  src/problems/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp
  src/problems/RadSuOlson/test_radiation_SuOlson.cpp
  src/problems/RadTophat/test_radiation_tophat.cpp
  src/problems/RadhydroPulseMGconst/test_radhydro_pulse_MG_const_kappa.cpp
  src/problems/RadhydroPulseMGint/test_radhydro_pulse_MG_int.cpp
  src/problems/RandomBlast/blast.cpp
  src/simulation.hpp
Labels: lgtm, size:S

#938 Add Stellar Evolution attribute and SNDeposition
  src/particles/PhysicsParticles.hpp
  src/particles/particle_creation.hpp
  src/particles/particle_deposition.hpp
  src/particles/particle_destruction.hpp
  src/particles/particle_types.hpp
  src/problems/Gravity3D/gravity_3d.cpp
  src/simulation.hpp
  tests/Gravity3D.in
Labels: lgtm, size:XL

#945 add QUOKKA_VERSION in metadata.yaml
  src/simulation.hpp
Labels: lgtm, size:XS

#953 add ROCm dev container
  .devcontainer/rocm-container/Dockerfile
  .devcontainer/rocm-container/devcontainer.json
Labels: AMDGPU, lgtm, size:M

#947 add DeltaAI scripts
  scripts/delta_ai.profile
  scripts/dtai-1node.submit
  scripts/dtai-64node.submit
  scripts/dtai-8node.submit
  src/QuokkaSimulation.hpp
Labels: lgtm, size:M

#946 ignore FPE in YAML I/O
  src/simulation.hpp
Labels: CI, I/O, lgtm, size:XS

#954 Create StellarPop particle type for Aditi's outflow simulations
  src/QuokkaSimulation.hpp
  src/linear_advection/AdvectionSimulation.hpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_types.hpp
  src/simulation.hpp
Labels: particles, lgtm, size:L

#944 update ROCm version on Frontier
  scripts/frontier-1node.submit
  scripts/frontier-4096node.submit
  scripts/frontier-512node.submit
  scripts/frontier-64node.submit
  scripts/frontier-8node.submit
  scripts/frontier.profile
Labels: lgtm, size:M
