Repository quokka-astro/quokka, pull requests merged in 2025-02, with the labels that each got.

#885 fix username for gcc devcontainer
  .devcontainer/gcc-container/Dockerfile
  .devcontainer/gcc-container/devcontainer.json
Labels: lgtm, size:XS

#886 Quokka movies
  docs/docs/gallery.md
Labels: documentation, lgtm, size:XS

#888 add git hash to metadata output
  CMakeLists.txt
  src/simulation.hpp
Labels: enhancement, lgtm, size:M

#889 Reduce regression testing disk space usage
  .ci/azure-pipelines-regression.yml
Labels: lgtm, size:XS

#890 Revert "Reduce regression testing disk space usage"
  .ci/azure-pipelines-regression.yml
Labels: CI, lgtm, size:XS

#891 Extensible particle architecture based on templated polymorphism
  .github/workflows/warnings.yml
  src/.clang-tidy
  src/QuokkaSimulation.hpp
  src/linear_advection/AdvectionSimulation.hpp
  src/particles/CICParticles.hpp
  src/particles/PhysicsParticles.hpp
  src/problems/BinaryOrbitCIC/binary_orbit.cpp
  src/problems/CMakeLists.txt
  src/problems/GravRadParticle3D/CMakeLists.txt
  src/problems/GravRadParticle3D/test_grav_rad_particle_3D.cpp
  src/problems/GravRadParticle3D/test_grav_rad_particle_3D.hpp
  src/problems/Gravity3D/CMakeLists.txt
  src/problems/Gravity3D/gravity_3d.cpp
  src/problems/Gravity3D/gravity_3d.hpp
  src/problems/HydroBlast3D/test_hydro3d_blast.cpp
  src/problems/RadParticle/CMakeLists.txt
  src/problems/RadParticle/test_radparticle.cpp
  src/problems/RadParticle/test_radparticle.hpp
  src/problems/RadParticle2D/CMakeLists.txt
  src/problems/RadParticle2D/test_radparticle_2D.cpp
  src/problems/RadParticle2D/test_radparticle_2D.hpp
  src/problems/RadhydroShell/test_radhydro_shell.cpp
  src/problems/SphericalCollapse/spherical_collapse.cpp
  src/radiation/source_terms_multi_group.hpp
  src/radiation/source_terms_single_group.hpp
  src/simulation.hpp
  tests/GravRadParticle3D.in
  tests/GravRadParticles3D.txt
  tests/GravRadParticles3D_cic_only.txt
  tests/GravRadParticles3D_rad_only.txt
  tests/Gravity3D.in
  tests/Gravity3D.txt
  tests/RadParticles1D.in
  tests/RadParticles1D.txt
  tests/RadParticles2D.in
  tests/RadParticles2D.txt
Labels: enhancement, lgtm, size:XXL

#901 Fix RadhydroShell failure: SetRadEnergySource should return erg.cm^-3.s^-1
  src/problems/RadParticle/test_radparticle.cpp
  src/problems/RadSuOlson/test_radiation_SuOlson.cpp
  src/problems/RadhydroShell/test_radhydro_shell.cpp
Labels: bug: wrong answer/failure/crash, lgtm, size:S

#910 Add CLAUDE.md with build instructions and coding guidelines
  CLAUDE.md
Labels: documentation, lgtm, size:S

#909 Clean up operatorSplitSourceTerms()
  src/QuokkaSimulation.hpp
Labels: lgtm, size:M

#896 Particle creator
  src/particles/PhysicsParticles.hpp
  src/physics_info.hpp
  src/problems/Gravity3D/gravity_3d.cpp
  src/simulation.hpp
  tests/Gravity3D.in
Labels: enhancement, particles, lgtm, size:L
