Repository quokka-astro/quokka, pull requests merged in 2025-04, with the labels that each got.

#971 add chongchonghe to CODEOWNERS for particles
  .github/CODEOWNERS
Labels: particles, lgtm, size:XS

#976 rename docs/docs to docs/markdown
  .gitignore
  docs/docs/requirements.txt
  docs/markdown/about.md
  docs/markdown/citation.md
  docs/markdown/debugging.md
  docs/markdown/equations.md
  docs/markdown/error_checking.md
  docs/markdown/extra.css
  docs/markdown/flowchart.md
  docs/markdown/gallery.md
  docs/markdown/howto_clang_tidy.md
  docs/markdown/index.md
  docs/markdown/insitu_analysis.md
  docs/markdown/instability.md
  docs/markdown/installation.md
  docs/markdown/javascripts/mathjax.js
  docs/markdown/parameters.md
  docs/markdown/performance.md
  docs/markdown/postprocessing.md
  docs/markdown/references.bib
  docs/markdown/running_on_hpc_clusters.md
  docs/markdown/tests/attach/hydro_shuosher.png
  docs/markdown/tests/attach/hydro_sms.png
  docs/markdown/tests/attach/radcoupling.png
  docs/markdown/tests/attach/radcoupling_rsla.png
  docs/markdown/tests/attach/radhydro_pulse_density-1.png
  docs/markdown/tests/attach/radhydro_pulse_density.png
  docs/markdown/tests/attach/radhydro_pulse_temperature-1.png
  docs/markdown/tests/attach/radhydro_pulse_temperature.png
  docs/markdown/tests/attach/radhydro_pulse_velocity-1.png
  docs/markdown/tests/attach/radhydro_pulse_velocity.png
  docs/markdown/tests/attach/radhydro_uniform_advecting_temperature-nobeta.png
  docs/markdown/tests/attach/radhydro_uniform_advecting_temperature.png
  docs/markdown/tests/attach/radhydro_uniform_advecting_velocity-nobeta.png
  docs/markdown/tests/attach/radhydro_uniform_advecting_velocity.png
  docs/markdown/tests/attach/radshock_cgs_temperature.png
  docs/markdown/tests/energy_exchange.md
  docs/markdown/tests/index.md
  docs/markdown/tests/radhydro_pulse.md
  docs/markdown/tests/radhydro_uniform_adv.md
  docs/markdown/tests/radshock.md
  docs/markdown/tests/shu_osher.md
  docs/markdown/tests/sms.md
  docs/mkdocs.yml
Labels: documentation, lgtm, size:XS

#970 Fix typo in comment about particleCfl
  src/simulation.hpp
Labels: lgtm, size:XS

#980 update Frontier modules
  scripts/frontier.profile
Labels: lgtm, size:S

#982 Fix bug in particle acceleration field for refined levels
  src/simulation.hpp
Labels: bug: wrong answer/failure/crash, lgtm, size:M

#989 only kick particles when Poisson solver is turned on
  src/simulation.hpp
Labels: particles, lgtm, size:XS

#987 Define a virtual function to tell if a particle type belongs to the Star particle class
  src/particles/PhysicsParticles.hpp
  src/particles/particle_types.hpp
Labels: particles, lgtm, size:S

#988 Add an example of manually setting particles' integer components
  src/QuokkaSimulation.hpp
  src/linear_advection/AdvectionSimulation.hpp
  src/particles/particle_types.hpp
  src/problems/Gravity3D/gravity_3d.cpp
  src/simulation.hpp
  tests/TestParticles.txt
Labels: enhancement, particles, lgtm, size:M

#997 Update .clang-tidy
  src/.clang-tidy
Labels: lgtm, size:XS

#985 Use FaceLinear AMR interpolation for particle accelerations
  src/problems/BinaryOrbitCIC/binary_orbit.cpp
  src/simulation.hpp
Labels: bug: wrong answer/failure/crash, particles, lgtm, size:L

#998 Update .clang-tidy again
  src/.clang-tidy
Labels: lgtm, size:XS

#1004 Use getParticleDataAtLevel in binary_orbit.cpp
  src/problems/BinaryOrbitCIC/binary_orbit.cpp
Labels: particles, lgtm, size:M

#1011 Remove default CUDA GPU architectures
  CMakeLists.txt
Labels: size:XS

#1015 Move particle parameter specialization into PhysicsParticleRegister
  src/particles/PhysicsParticles.hpp
  src/simulation.hpp
Labels: particles, lgtm, size:L

#1012 Update Dockerfile
  .devcontainer/cuda-container/Dockerfile
  .devcontainer/cuda-container/devcontainer.json
  .devcontainer/rocm-container/Dockerfile
  .devcontainer/rocm-container/devcontainer.json
  .gitignore
Labels: lgtm, size:S

#999 Update copyright year in docs
  docs/mkdocs.yml
Labels: documentation, lgtm, size:XS

#995 A new SN feedback model
  src/particles/PhysicsParticles.hpp
  src/particles/particle_deposition.hpp
  src/particles/particle_types.hpp
  src/problems/CMakeLists.txt
  src/problems/SN/CMakeLists.txt
  src/problems/SN/test_SN.cpp
  src/problems/SN/test_SN.hpp
  src/simulation.hpp
  tests/SN.in
  tests/SN.txt
Labels: enhancement, particles, lgtm, size:XL

#1009 Allow to force some particles to always live in finest cells
  src/QuokkaSimulation.hpp
  src/linear_advection/AdvectionSimulation.hpp
  src/particles/PhysicsParticles.hpp
  src/problems/Advection2D/test_advection2d.cpp
  src/problems/BinaryOrbitCIC/binary_orbit.cpp
  src/problems/HydroBlast2D/test_hydro2d_blast.cpp
  src/problems/HydroBlast3D/test_hydro3d_blast.cpp
  src/problems/HydroKelvinHelmholz/test_hydro2d_kh.cpp
  src/problems/HydroShocktube/test_hydro_shocktube.cpp
  src/problems/HydroShocktubeCMA/test_hydro_shocktube_cma.cpp
  src/problems/ParticleCreation/particle_creation_from_cell.cpp
  src/problems/PassiveScalar/test_scalars.cpp
  src/problems/PopIII/popiii.cpp
  src/problems/RadBeam/test_radiation_beam.cpp
  src/problems/RadShadow/test_radiation_shadow.cpp
  src/problems/RadhydroShell/test_radhydro_shell.cpp
  src/problems/RandomBlast/blast.cpp
  src/problems/RayleighTaylor2D/test_hydro2d_rt.cpp
  src/problems/RayleighTaylor3D/test_hydro3d_rt.cpp
  src/problems/ShockCloud/cloud.cpp
  src/problems/SphericalCollapse/spherical_collapse.cpp
  src/problems/StarCluster/star_cluster.cpp
  src/simulation.hpp
  tests/ParticleCreationAMR.in
  tests/TestParticles.txt
Labels: particles, lgtm, size:L

#1020 Modularize SNDeposition
  src/particles/PhysicsParticles.hpp
  src/particles/particle_deposition.hpp
Labels: particles, lgtm, size:XL

#1017 A novel scheme for sink particle accretion -- framework
  .codespell-ignore-words
  src/QuokkaSimulation.hpp
  src/linear_advection/AdvectionSimulation.hpp
  src/particles/PhysicsParticles.hpp
  src/particles/particle_accretion.hpp
  src/particles/particle_types.hpp
  src/particles/particle_utils.hpp
  src/problems/CMakeLists.txt
  src/problems/ParticleSink/CMakeLists.txt
  src/problems/ParticleSink/test_particle_sink.cpp
  src/problems/ParticleSink/test_particle_sink.hpp
  src/simulation.hpp
  tests/ParticleSink.in
  tests/Sink_2.txt
  tests/Sink_4.txt
  tests/Sink_40.txt
Labels: enhancement, particles, lgtm, size:XL
