Repository quokka-astro/quokka, pull requests merged in 2025-08, with the labels that each got.

#1247 chore: disable Docker container base image updates
  .github/dependabot.yml
Labels: dependencies, lgtm, size:S

#1223 Add GPU-compatible quokka::optional
  src/hydro/EOS.hpp
  src/problems/RadMarshak/test_radiation_marshak.cpp
  src/problems/RadMarshakCGS/test_radiation_marshak_cgs.cpp
  src/problems/RadMatterCoupling/test_radiation_matter_coupling.cpp
  src/problems/RadMatterCouplingRSLA/test_radiation_matter_coupling_rsla.cpp
  src/problems/RadSuOlson/test_radiation_SuOlson.cpp
  src/problems/RadTophat/test_radiation_tophat.cpp
  src/util/Optional.hpp
Labels: lgtm, size:L

#1243 Update DataTable to read HDF5 files and do table interpolation up to four dimensions
  inputs/ResampledCooling.in
  src/CMakeLists.txt
  src/cooling/ResampledCooling.cpp
  src/cooling/ResampledCooling.hpp
  src/util/DataTable.cpp
  src/util/DataTable.hpp
Labels: enhancement, lgtm, size:XXL

#1254 Try to fix the CI issue when changing submodules
  .ci/azure-pipelines-amdgpu.yml
  .ci/azure-pipelines.yml
  .github/workflows/mhd.yml
Labels: CI, lgtm, size:S

#1236 Set star particle velocities to include runaways
  src/particles/particle_creation.hpp
  src/problems/ParticleSF/test_particle_SF.cpp
Labels: particles, lgtm, size:L

#1279 Disable CodeQL for C++
  .github/workflows/codeql.yml
Labels: github_actions, lgtm, size:XS

#1278 Fix b-field indexing during reconstruction (Riemann solver input)
  src/QuokkaSimulation.hpp
  src/hydro/hydro_system.hpp
Labels: MHD, lgtm, size:L

#1263 Fix race conditions in ComputeEMF
  docs/markdown/debugging.md
  scripts/bash/test_gpu_race.sh
  src/hydro/mhd_system.hpp
Labels: MHD, lgtm, size:L
