Repository quokka-astro/quokka, pull requests merged in 2025-01, with the labels that each got.

#843 Enforce minimum ROCm version >= 6.3
  .github/workflows/dependencies/dependencies_hip.sh
  CMakeLists.txt
Labels: AMDGPU, lgtm, size:M

#845 Update docs for AMD GPUs
  README.md
  docs/docs/installation.md
Labels: documentation, AMDGPU, lgtm, size:XS

#848 exclude misc-include-cleaner in clang-tidy
  src/.clang-tidy
Labels: lgtm, size:XS

#857 Temporary workaround for gcc 14 libstdc++ incompatibility with HIP
  .github/workflows/dependencies/dependencies_hip.sh
  .github/workflows/hip.yml
Labels: CI, lgtm, size:XS

#876 set default max_timesteps to INT_MAX
  src/simulation.hpp
Labels: lgtm, size:M

#875 allow disabling energy check in Sedov problem
  src/problems/HydroBlast3D/test_hydro3d_blast.cpp
  tests/blast_32.in
Labels: enhancement, lgtm, size:L

#874 Movie for R8
  docs/docs/gallery.md
  docs/mkdocs.yml
Labels: lgtm, size:M
